# Generated by Django 5.1.7 on 2025-03-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('singer', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
    ]
